const to = require('to-case')

exports.camel = (x) => to.camel(x)
exports.capital = (x) => to.capital(x)
exports.constant = (x) => to.constant(x)
exports.dot = (x) => to.dot(x)
exports.inverse = (x) => to.inverse(x)
exports.lower = (x) => to.lower(x)
exports.pascal = (x) => to.pascal(x)
exports.sentence = (x) => to.sentence(x)
exports.slug = (x) => to.slug(x)
exports.snake = (x) => to.snake(x)
exports.space = (x) => to.space(x)
exports.title = (x) => to.title(x)
exports.upper = (x) => to.upper(x)